### PR TITLE
Download generification

### PR DESCRIPTION
**Pull request by knusbaum**
We recently merged a change that, for one download, picks either wget or curl depending on which is available.

This pull creates a function capturing this behaviour so it can be used elsewhere in the script.

### CODE REVIEW

**Comment by knusbaum** [comment]
Depends on #11 As it is written here, download_file isn't defined where it's invoked in assigning APACHE_MIRRORS.

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by revans2** [comment]
For me this line 29 is complaining the download_file is not defined yet.  If I move it down everything works.  @knusbaum could you take a look at that?

After that I am +1

**Comment by revans2** [comment]
@knusbaum I see this kind of conflicts with #11 Perhaps you could just combine these two together and kill two birds with one stone.

**Pull request closed without merging**
