### PR TITLE
Fix a bug that load-ids always returns nil

### PR DESCRIPTION
**Pull request by gyk**

### CODE REVIEW

**Comment by kishorvpatil** [comment]
LGTM. +1

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by gyk** [comment]
Sorry my code is wrong. `finally` will get called even if file loading fails.

**Comment by manifoldQAQ** [comment]
This is really an important issue, leading to unnecessary disk IOs.

**Pull request closed without merging**
