### PR TITLE
Support tests on MacOS

### PR DESCRIPTION
**Pull request by zhuoliu**
Support download packages on MacOS through "curl", on other OSs, "wget" will be installed. Also, remind user to install Leiningen in Readme.

### CODE REVIEW

**Comment by knusbaum** [comment]
I don't think we can always expect curl on OS X and wget on others. I'd rather try something more generic, like:
```
WGET=`whereis wget`
CURL=`whereis curl`

if [ -n "$WGET" ];
then
    wget -O "$FILE" "$URL"
elif [ -n "$CURL" ];
then
    curl -o "$FILE" "$URL"
else
    echo "Please install curl or wget to continue.";
    exit 1
fi
```

This way, if either curl or wget are installed on any system, it works. And if neither are, it gives them a nice error.

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by zhuoliu** [comment]
@knusbaum sounds good, now go with your suggestion.

**Comment by knusbaum** [comment]
+1

**Comment by revans2** [comment]
+1

**Pull request merged**
